# POST https://node-auth-g52.onrender.com/api/users/register
POST http://127.0.0.1:3000/api/users/register
Content-Type: application/json

{
    "email": "pepito1@gmail.com", 
    "password": "12345", 
    "role": "admin"
}

###
# POST http://127.0.0.1:3000/api/users/login
POST https://node-auth-g52.onrender.com/api/users/login
Content-Type: application/json


{
    "email": "pepito1@gmail.com", 
    "password": "12345"
}

###
# GET  http://127.0.0.1:3000/api/users/perfil
GET  https://node-auth-g52.onrender.com/api/users/perfil
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBlcGl0bzFAZ21haWwuY29tIiwiaWF0IjoxNzIwNDg0OTIxfQ.kWKUwbyTRehnmKxOMH7N6DJ6vzXBXmPcBjJNoVUldM4
